updated the free_swap-script to turn swap off and on even when none is used, this to enable swap when accidentally disabled

diff --git a/free_swap b/free_swap
--- a/free_swap
+++ b/free_swap
@@ -9,13 +9,12 @@ total_free=$((free_mem + buffers + cache))
 used_swap="$(echo "$free_data" | grep 'Swap:' | awk '{print $3}')"
 
 echo -e "Free memory:\t$total_free kB ($((total_free / 1024)) MB)\nUsed swap:\t$used_swap kB ($((used_swap / 1024)) MB)"
-if [[ $used_swap -eq 0 ]]; then
-    echo "Congratulations! No swap is in use."
-elif [[ $used_swap -lt $total_free ]]; then
-    echo "Freeing swap..."
-    sudo swapoff -a
-    sudo swapon -a
-else
-    echo "Not enough free memory. Exiting."
+
+if [ $total_free -lt $used_swap ]; then
+    echo "ERROR: not enough RAM to write swap back, nothing done" >&2
     exit 1
 fi
+
+echo "Freeing swap..."
+sudo swapoff -a 
+sudo swapon -a
